// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCjlfN24c867yTt0Ac4denxRGzTaRyPk',
    appId: '1:677597546779:web:ec1a470f276d3b14baebbe',
    messagingSenderId: '677597546779',
    projectId: 'ohms-assignment',
    authDomain: 'ohms-assignment.firebaseapp.com',
    storageBucket: 'ohms-assignment.appspot.com',
    measurementId: 'G-16JDE4KHKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT4SG3E2ilqa0xav9KjSovMNi_ewIDvzg',
    appId: '1:677597546779:android:fe00470f676e9fecbaebbe',
    messagingSenderId: '677597546779',
    projectId: 'ohms-assignment',
    storageBucket: 'ohms-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSeRMQuDeybx1LSYIpZvtswS-jVHlzrk',
    appId: '1:677597546779:ios:8e58ab2f882e5095baebbe',
    messagingSenderId: '677597546779',
    projectId: 'ohms-assignment',
    storageBucket: 'ohms-assignment.appspot.com',
    iosBundleId: 'com.example.assignmentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSeRMQuDeybx1LSYIpZvtswS-jVHlzrk',
    appId: '1:677597546779:ios:e8ced40a4486cad9baebbe',
    messagingSenderId: '677597546779',
    projectId: 'ohms-assignment',
    storageBucket: 'ohms-assignment.appspot.com',
    iosBundleId: 'com.example.assignmentFlutter.RunnerTests',
  );
}
